name: build docker image and push to Docker Hub
on: push

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      # read/get repository content
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Set Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Login DockerHub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: harrisonhxy/librechat:latest
          no-cache: true